### ISSUE TITLE
go projects don't work

### ISSUE THREAD

**Issue by jfelten** [ericmdantas/generator-ng-fullstack#46]
I was able to create a go project, and was able to make it run by manually removing hte githib imports in main.go.  None of the tests work due to invalid imports in the todo classes Ex:
go test ./... -cover -bench .

api/todo/routes/todoroutes.go:4:2: invalid import path: "github.com/<%= username %>/<%= appName %>/server/api/todo/controller"

If I try to add my own endpoint following the documentation:

 yo ng-fullstack:endpoint skate --feature skateboard
module.js:338
    throw err;
          ^
Error: Cannot find module '../known-paths'
    at Function.Module._resolveFilename (module.js:336:15)

It seems to have a missing nodejs dependency.

**Comment by ericmdantas** [comment]
@jfelten Thank you for the feedback, I'll take a look when I get home.

**Comment by ericmdantas** [comment]
Yeah, there's definetely a bug. I'll fix it as soon as possible.

**Comment by charliegroll** [comment]
Bump on this issue

I get this same error when trying  ```yo ng-fullstack:resource Event --feature event``` in a node app

[10:26]:elapsed % yo ng-fullstack:resource Event --feature event
module.js:338
    throw err;
    ^
```
Error: Cannot find module '../known-paths'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-ng-fullstack/resource/index.js:5:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by ericmdantas** [comment]
Hello, @charliegroll.

That's a different error, though. Do the other sub generators work? Like controller, service, etc?

**Comment by charliegroll** [comment]
I get the same error for service and filter

**Comment by ericmdantas** [comment]
Alright, I'm takin a look.

**Comment by ericmdantas** [comment]
I got to simulate it with the latest version. 

Good news is that it's working alright with the master version.

**Comment by charliegroll** [comment]
Awesome, thanks!

**Comment by ericmdantas** [comment]
@charliegroll I published 1.5.0-0, could you give it a try?

**Comment by charliegroll** [comment]
I updated ng-fullstack from the yo prompts and still get the error

**Comment by ericmdantas** [comment]
@charliegroll could you uninstall and install it again?

`npm uninstall -g generator-ng-fullstack`
`npm i -g generator-ng-fullstack`

**Comment by charliegroll** [comment]
I completely reinstalled it and I'm still seeing 1.4 in the package.json

```
[20:27]:generator-ng-fullstack (master|✔) % head package.json
{
  "name": "generator-ng-fullstack",
  "version": "1.4.0",
  "description": "Yeoman generator",
  "license": "MIT",
  "main": "app/index.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ericmdantas/generator-ng-fullstack.git"
  },
```

**Comment by ericmdantas** [comment]
oh, try installing it as generator-ng-fullstack@latest

**Comment by charliegroll** [comment]
I can't start a project from nothing now

```
[21:18]:elapsed % yo
? 'Allo Charlie! What would you like to do? Ng Fullstack

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo ng-fullstack


     _-----_
    |       |    .-----------------------.
    |--(o)--|    |      Bye from us!     |
   `---------´   |       Chat soon.      |
    ( _´U`_ )    |      Yeoman team      |
    /___A___\    |    http://yeoman.io   |
     |  ~  |     '-----------------------'
   __'.___.'__
 ´   `  |° ´ Y `

readline.js:924
            throw err;
            ^

Error: Cannot find module '../_ng/generator.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-ng-fullstack/app/index.js:29:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by ericmdantas** [comment]
`1.5.1-0` published. Coud you try that?

**Comment by charliegroll** [comment]
Created a new project and installed a resource. Thanks!

```
[19:50]:elapsed % yo ng-fullstack:resource Event --feature event
   create client/dev/js/event/resource/Event.resource.js
```

**Comment by charliegroll** [comment]
Created a new project and installed a resource. Thanks!

    [19:50]:elapsed % yo ng-fullstack:resource Event --feature event
       create client/dev/js/event/resource/Event.resource.js

**Comment by ericmdantas** [comment]
Awesome! Thanks for trying it out.

**Comment by ericmdantas** [comment]
Just so we're clear, this error:

> yo ng-fullstack:endpoint skate --feature skateboard
module.js:338
throw err;
^
Error: Cannot find module '../known-paths'
at Function.Module._resolveFilename (module.js:336:15)

Is already solved. The go one is still around.
