### ISSUE TITLE
error at starting server

### ISSUE THREAD

**Issue by uiktiomasfeliz** [ericmdantas/generator-ng-fullstack#71]
```

gulp
[16:56:29] Requiring external module babel-register
[16:56:34] Using gulpfile ~\Desktop\Mean2.1\gulpfile.babel.js
[16:56:34] Starting 'client.build_ts:dev'...
[16:56:34] Starting 'client.browser_sync'...
[16:56:34] Finished 'client.browser_sync' after 746 μs
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/change_detection/parser/locals.d.ts(3,14): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/change_detection/parser/locals.d.ts(4,42): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/debug/debug_node.d.ts(14,13): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/debug/debug_node.d.ts(24,17): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/debug/debug_node.d.ts(25,17): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/di/provider.d.ts(436,103): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/di/provider.d.ts(436,135): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/render/api.d.ts(13,13): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/render/api.d.ts(14,84): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(95,41): error TS2304: Cannot find name 'Set'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(96,22): error TS2304: Cannot find name 'Set'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(97,25): error TS2304: Cannot find name 'Set'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/lang.d.ts(13,17): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/lang.d.ts(14,17): error TS2304: Cannot find name 'Set'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/lang.d.ts(78,59): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(3,14): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(8,32): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(9,38): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(10,35): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(10,93): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(11,34): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(12,32): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(12,149): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/http/headers.d.ts(43,59): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/http/url_search_params.d.ts(11,16): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/platform/browser/browser_adapter.d.ts(75,33): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/platform/dom/dom_adapter.d.ts(85,42): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/CoreOperators.d.ts(35,67): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/CoreOperators.d.ts(50,66): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/CoreOperators.d.ts(89,67): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/CoreOperators.d.ts(94,38): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/CoreOperators.d.ts(94,50): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(46,62): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(47,42): error TS2304: Cannot find name 'Iterator'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(103,74): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(103,84): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(143,66): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(158,65): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(201,66): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(206,38): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(206,50): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/observable/ForkJoinObservable.d.ts(6,50): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/observable/ForkJoinObservable.d.ts(7,58): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/observable/FromObservable.d.ts(7,38): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/observable/FromObservable.d.ts(7,51): error TS2304: Cannot find name 'Iterator'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/observable/PromiseObservable.d.ts(9,31): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/observable/PromiseObservable.d.ts(10,26): error TS2304: Cannot find name 'Promise'.
[16:56:41] TypeScript: 59 semantic errors
[16:56:41] TypeScript: emit succeeded (with errors)
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/change_detection/parser/locals.d.ts(3,14): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/change_detection/parser/locals.d.ts(4,42): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/debug/debug_node.d.ts(14,13): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/debug/debug_node.d.ts(24,17): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/debug/debug_node.d.ts(25,17): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/di/provider.d.ts(436,103): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/di/provider.d.ts(436,135): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/render/api.d.ts(13,13): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/core/render/api.d.ts(14,84): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(95,41): error TS2304: Cannot find name 'Set'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(96,22): error TS2304: Cannot find name 'Set'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/collection.d.ts(97,25): error TS2304: Cannot find name 'Set'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/lang.d.ts(13,17): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/lang.d.ts(14,17): error TS2304: Cannot find name 'Set'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/lang.d.ts(78,59): error TS2304: Cannot find name 'Map'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(3,14): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(8,32): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(9,38): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(10,35): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(10,93): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(11,34): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(12,32): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(12,149): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/facade/promise.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/angular2/src/testing/matchers.d.ts(4,37): error TS2503: Cannot find namespace 'jasmine'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/CoreOperators.d.ts(35,67): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/CoreOperators.d.ts(50,66): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/CoreOperators.d.ts(89,67): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/CoreOperators.d.ts(94,38): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/CoreOperators.d.ts(94,50): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(46,62): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(47,42): error TS2304: Cannot find name 'Iterator'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(103,74): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(103,84): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(143,66): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(158,65): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(201,66): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(206,38): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/Observable.d.ts(206,50): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/observable/ForkJoinObservable.d.ts(6,50): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/observable/ForkJoinObservable.d.ts(7,58): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/observable/FromObservable.d.ts(7,38): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/observable/FromObservable.d.ts(7,51): error TS2304: Cannot find name 'Iterator'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/observable/PromiseObservable.d.ts(9,31): error TS2304: Cannot find name 'Promise'.
C:/Users/mou/Desktop/Mean2.1/node_modules/rxjs/observable/PromiseObservable.d.ts(10,26): error TS2304: Cannot find name 'Promise'.
tests\client\todo\components\todo_component_test.ts(28,23): error TS2307: Cannot find module '../client/dev/todo/todo_cmp.js'.
tests\client\todo\components\todo_component_test.ts(29,27): error TS2307: Cannot find module '../client/dev/todo/todo_service.js'.
tests\client\todo\components\todo_component_test.ts(69,26): error TS2339: Property 'toBeDefined' does not exist on type 'NgMatchers'.
tests\client\todo\components\todo_component_test.ts(77,9): error TS2304: Cannot find name 'spyOn'.
tests\client\todo\components\todo_component_test.ts(81,34): error TS2339: Property 'toHaveBeenCalled' does not exist on type 'NgMatchers'.
tests\client\todo\services\todo_service_test.ts(9,27): error TS2307: Cannot find module '../client/dev/todo/todo_service'.

```

**Comment by ericmdantas** [comment]
What version of angular2 are you using? Beta3 or beyond?

**Comment by uiktiomasfeliz** [comment]
with the latest version of package

```
"dependencies": {
    "lodash": "^3.10.0",
    "bluebird": "^2.9.24",
    "body-parser": "^1.12.2",
    "express": "~4.12.3",
    "express-content-length-validator": "1.0.0",
    "mongoose": "^4.1.11",
    "morgan": "^1.5.2", 
    "angular2": "^2.0.0-beta.3",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.13",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^5.0.0-beta.1",
    "systemjs": "^0.19.5",
    "typescript": "^1.7.3",
    "zone.js": "^0.5.10", 
    "newrelic": "^1.18.2",
    "helmet": "^0.7.1"
  },
```

**Comment by KapuzenSohn** [comment]
Latest Version of angular is `beta.6`. 
I am getting the same errors with the latest angular version. I updated all my dependencies that where out of date and completly installed them new.

**Comment by imatefx** [comment]
+1

**Comment by KapuzenSohn** [comment]
Switching back to `beta.3` my gulp task don´t throws any errors.

**Comment by imatefx** [comment]
https://github.com/angular/angular/issues/7052#issuecomment-183647125

**Comment by KapuzenSohn** [comment]
@imatefx
that did the job. next time: read the changelog :D

**Comment by imatefx** [comment]
:+1:

**Comment by ericmdantas** [comment]
I released 1.6.0-4 which adds the reference for browser.d.ts, should fix this.

**Comment by uiktiomasfeliz** [comment]
i still have the error with latest version. the npm wrote this:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN angular2@2.0.0-beta.6 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN angular2@2.0.0-beta.6 requires a peer of rxjs@5.0.0-beta.0 but none was installed.
```
also tried installing rxjs@5.0.0-beta.0 and reflect-metadata@0.1.2, same issues.
what i do wrong?

**Comment by ericmdantas** [comment]
Those are just warnings, it should work correctly.

**Comment by uiktiomasfeliz** [comment]
and this?
```
....
├── UNMET PEER DEPENDENCY reflect-metadata@0.1.3
├── require-dir@0.3.0
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.2
├─┬ systemjs@0.19.20
│ ├── es6-module-loader@0.17.11
│ └── when@3.7.7
├── typescript@1.7.5
├─┬ wiredep@2.2.2
│ ├─┬ bower-config@0.5.2
│ │ ├── graceful-fs@2.0.3
│ │ ├── mout@0.9.1
│ │ └── osenv@0.0.3
│ ├─┬ chalk@0.5.1
│ │ ├── ansi-styles@1.1.0
│ │ ├─┬ has-ansi@0.1.0
│ │ │ └── ansi-regex@0.2.1
│ │ ├── strip-ansi@0.3.0
│ │ └── supports-color@0.2.0
│ ├── glob@4.5.3
│ ├── lodash@2.4.2
│ ├── propprop@0.3.0
│ └─┬ through2@0.6.5
│   └── readable-stream@1.0.33
└── zone.js@0.5.14
```

**Comment by ericmdantas** [comment]
Same.

After all this, can you run `gulp` and then `npm start`?

**Comment by uiktiomasfeliz** [comment]
same error's on gulp,
when i try npm start, throw me this log:

´´´
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\mou\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.5.3
3 info using node@v4.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle gecor@0.0.1~prestart: gecor@0.0.1
6 silly lifecycle gecor@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle gecor@0.0.1~start: gecor@0.0.1
8 verbose lifecycle gecor@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle gecor@0.0.1~start: PATH: C:\Users\mou\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\mou\Desktop\MEAN\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\AndroidSDK\tools;C:\AndroidSDK\platform-tools;C:\Ruby22-x64\bin;C:\Users\mou\AppData\Roaming\npm;C:\Users\mou\AppData\Local\atom\bin;C:\Users\mou\AppData\Local\.meteor\
10 verbose lifecycle gecor@0.0.1~start: CWD: C:\Users\mou\Desktop\MEAN
11 silly lifecycle gecor@0.0.1~start: Args: [ '/d /s /c', 'node index' ]
12 silly lifecycle gecor@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle gecor@0.0.1~start: Failed to exec start script
14 verbose stack Error: gecor@0.0.1 start: `node index`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\mou\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\mou\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid gecor@0.0.1
16 verbose cwd C:\Users\mou\Desktop\MEAN
17 error Windows_NT 10.0.10240
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mou\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v4.2.1
20 error npm  v3.5.3
21 error code ELIFECYCLE
22 error gecor@0.0.1 start: `node index`
22 error Exit status 1
23 error Failed at the gecor@0.0.1 start script 'node index'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the gecor package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs gecor
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls gecor
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
´´´

i'll try update node, show if the error can be produce by the 4.2.1 version

**Comment by ericmdantas** [comment]
Alright. I'll take a look when I get home.

**Comment by ericmdantas** [comment]
Couldn't simulate the bug you mentioned, @uiktiomasfeliz. But I did find and fixed a bug with a version of rxjs that was being shipped https://github.com/angular/angular/issues/7019

With that, I released 1.6.0-5. The typings error still occur, though. I'll take a look later today.

**Comment by ericmdantas** [comment]
By the way, since we're at the same bug, I'm closing this in favor of #68.
